<#
  extract-schedule.ps1

  Builds docs/data/schedule.json for the Daily Holocron board by joining two
  inputs:

    1. docs/data/rotation.json - the rotation skeleton. One slot per
       (period, date) carrying semester, cycle and lesson number. Committed;
       generated by tools/build-rotation.ps1 from the ROT_DAYS rule table in
       docs/index.html crossed with the day-type calendar.

    2. the planning Google Sheet, "Master Data" tab - lesson content keyed on
       (Semester, Cycle, Lesson #, Track). Downloaded as .xlsx on every run.

  Why the split
  -------------
  The sheet has no dates; the board needs one record per (period, date). The
  bridge is the per-period meeting pattern, which comes from the ROT_DAYS rule
  table in the board rather than from the sheet. Periods skip different
  rotation days, and the rotation label's parenthetical is NOT the meeting list
  (2026-08-17 is labelled "DAY 2 (F-C)" yet A and G are what meet). See
  tools/build-rotation.ps1 for the derivation and the checks behind it.

  Join model
  ----------
    rotation slot (period, date) -> (semester, cycle, lessonNumber, track)
                                 -> Master Data row -> the seven content fields

  Track: HP covers periods A, D and G (Honors, planned in lockstep); EP covers
  period E (ECP, paced separately).

  Field mapping (Master Data column -> record field)
  --------------------------------------------------
    E First 5    -> first5      H Lesson Plan -> lesson[]
    F Bring      -> materials   I Study       -> study[]
    G Lit. Focus -> objective   J Homework    -> homework[]
                                K Due         -> due
  Columns A-D are the join key: Semester, Cycle, Lesson #, Track.

  Multi-line cells become arrays for lesson/study/homework, which the board
  joins with newlines to render as separate bullets. The other four stay plain
  strings.

  Publication horizon (built, currently OFF)
  ------------------------------------------
  -PublishLeadDays withholds a cycle's content until today is within N days of
  its first meeting, so unfinished future planning stays out of a publicly
  served file. Withheld slots publish blank, exactly like an unplanned lesson.

  Default is 0 = off, because the board's URL is not shared with students or
  families. Turning it on costs the ability to page the board forward when
  prepping, which is a real loss with no audience to protect against. Set it to
  2 if that changes.

  Usage:  powershell -ExecutionPolicy Bypass -File extract-schedule.ps1
#>

param(
    # Site root. schedule.json is written to <SiteDir>/data/schedule.json.
    [string]$SiteDir = (Join-Path $PSScriptRoot 'docs'),
    # The planning sheet's id. Deliberately NOT hardcoded - see "Keeping the
    # sheet unlisted" below. Resolved from the environment or a local file.
    [string]$SheetId,
    [string]$MasterTab = 'Master Data',
    [string]$RotationPath,
    [int]$FallSchoolYear = 2026,
    # Publication horizon, in days before a cycle starts. Content for a cycle
    # further out than this publishes blank, keeping unfinished future planning
    # out of a file that is served publicly.
    #
    # DISABLED (0) by design: the board's URL is not shared with students or
    # families, so there is no audience to withhold drafts from, and a horizon
    # would cost the ability to page the board forward when prepping. Set it to
    # 2 (or 7) if the address is ever handed out. Verified working - see the
    # boundary test in CLAUDE.md.
    [int]$PublishLeadDays = 0,
    # Testing hook: pretend it is this date (yyyy-MM-dd) when applying the
    # horizon. Leave unset in normal use; the runner's UTC date is used then.
    [string]$Today
)

$ErrorActionPreference = 'Stop'
# Windows PowerShell 5.1 defaults to TLS 1.0; pwsh on Linux (GitHub Actions)
# does not expose ServicePointManager the same way, so this is best-effort.
try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch { }

<#
  Keeping the sheet unlisted
  --------------------------
  This repository is public, and docs/ is served on GitHub Pages, so anything
  written into schedule.json or printed to the console is world-readable (Actions
  logs on a public repo included). The planning sheet is link-shared and holds
  the whole year's teacher-side planning, so its id is kept out of all four:

    * not in this script  -> supplied via $env:HOLOCRON_SHEET_ID (a repo
                             Actions variable in CI) or sheet-id.local
    * not in schedule.json -> the sources[] block records no id or URL
    * not in the console   -> only the last 4 characters are ever printed
    * not in CLAUDE.md

  This is obscurity, not access control: anyone who has the link can still open
  the sheet. It closes the realistic path - reading the id out of the public
  repo or the published JSON. For real protection the sheet would have to stop
  being link-shared, which means authenticating the fetch with a service
  account key held in Actions secrets.
#>
if (-not $SheetId) { $SheetId = $env:HOLOCRON_SHEET_ID }
if (-not $SheetId) {
    # Gitignored, so a local run needs no environment fiddling.
    $idFile = Join-Path $PSScriptRoot 'sheet-id.local'
    if (Test-Path $idFile) { $SheetId = (Get-Content $idFile -Raw -Encoding UTF8).Trim() }
}
if (-not $SheetId) {
    throw @'
No sheet id. Provide it one of three ways:
  * -SheetId <id>
  * $env:HOLOCRON_SHEET_ID   (in CI this comes from the SHEET_ID repo variable)
  * a sheet-id.local file next to this script, containing just the id
The id is kept out of the repo on purpose; see the comment above this check.
'@
}
# Enough to tell two sheets apart in a log without disclosing either.
$sheetTag = 'sheet ...' + $SheetId.Substring([Math]::Max(0, $SheetId.Length - 4))

if (-not $SiteDir) { $SiteDir = Join-Path (Get-Location).Path 'docs' }
$dataDir = Join-Path $SiteDir 'data'
if (-not (Test-Path $dataDir)) { New-Item -ItemType Directory -Path $dataDir -Force | Out-Null }

$jsonPath = Join-Path $dataDir 'schedule.json'
if (-not $RotationPath) { $RotationPath = Join-Path $dataDir 'rotation.json' }

# Which periods belong to which track, and the course label each track carries
# onto its records. Mirrors tools/build-rotation.ps1.
$TrackCourse = @{ 'HP' = '8 Honors Lit'; 'EP' = '8 ECP Lit' }

# Unit separator keeps field boundaries out of the content itself.
$SIG_SEP = [string][char]31
function Get-RecordSignature {
    param($R)
    return ($R.first5 + $SIG_SEP + $R.materials + $SIG_SEP + $R.objective + $SIG_SEP +
            (($R.lesson) -join "`n") + $SIG_SEP + (($R.study) -join "`n") + $SIG_SEP +
            (($R.homework) -join "`n") + $SIG_SEP + $R.due)
}

$previous = $null
if (Test-Path $jsonPath) {
    try { $previous = Get-Content $jsonPath -Raw -Encoding UTF8 | ConvertFrom-Json } catch { }
}

# ----------------------------------------------------------------- helpers ---

# Google Sheets keeps hard line breaks inside a cell. They are the whole point
# of the multi-line fields, so split on them and drop only blank lines.
function Split-Lines {
    param([string]$Text)
    $out = @()
    if ($null -eq $Text) { return , $out }
    foreach ($line in ($Text -split "`r?`n")) {
        $t = $line.Trim()
        if ($t -ne '') { $out += $t }
    }
    return , $out
}

function Join-Text {
    param([string]$Text)
    return ((Split-Lines $Text) -join "`n")
}

# "BC7" -> "BC". Cell refs are letters+digits; only the letters identify the
# column. Rows are keyed by letter rather than by header text because Master
# Data has two columns headed "Lesson" - C is the lesson number, H is the
# lesson content - so a name-keyed lookup silently collides.
function Get-ColumnLetter {
    param([string]$CellRef)
    return ($CellRef -replace '[^A-Za-z]', '').ToUpper()
}

function Read-ZipEntryText {
    param($Archive, [string]$EntryName)
    $entry = $Archive.Entries | Where-Object { $_.FullName -eq $EntryName }
    if (-not $entry) { return $null }
    $stream = $entry.Open()
    try {
        $reader = New-Object System.IO.StreamReader($stream, [System.Text.Encoding]::UTF8)
        try { return $reader.ReadToEnd() } finally { $reader.Dispose() }
    } finally { $stream.Dispose() }
}

<#
  Reads one worksheet of an .xlsx. Returns a hashtable:
    headers = column letter -> header text from row 1
    rows    = list of hashtables, column letter -> cell text
  Blank cells are absent from the row hashtable rather than present-and-empty.
#>
function Read-XlsxTab {
    param([string]$XlsxPath, [string]$TabName)

    Add-Type -AssemblyName System.IO.Compression.FileSystem | Out-Null
    $zip = [System.IO.Compression.ZipFile]::OpenRead($XlsxPath)
    try {
        $main = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'
        $rel  = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships'

        # workbook.xml names the tabs and points at them by relationship id;
        # workbook.xml.rels resolves those to worksheet parts.
        $wbXml = Read-ZipEntryText $zip 'xl/workbook.xml'
        if (-not $wbXml) { throw 'xl/workbook.xml missing - not a valid .xlsx' }
        $wb = [xml]$wbXml
        $wbNs = New-Object System.Xml.XmlNamespaceManager($wb.NameTable)
        $wbNs.AddNamespace('m', $main)
        $wbNs.AddNamespace('r', $rel)

        $sheetNode = $null
        $names = @()
        foreach ($s in $wb.SelectNodes('//m:sheets/m:sheet', $wbNs)) {
            $names += $s.GetAttribute('name')
            if ($s.GetAttribute('name') -eq $TabName) { $sheetNode = $s }
        }
        if (-not $sheetNode) {
            throw ("No tab named '{0}'. Tabs present: {1}" -f $TabName, ($names -join ', '))
        }
        $rid = $sheetNode.GetAttribute('id', $rel)

        $relsXml = Read-ZipEntryText $zip 'xl/_rels/workbook.xml.rels'
        $rels = [xml]$relsXml
        $target = $null
        foreach ($r in $rels.Relationships.Relationship) {
            if ($r.Id -eq $rid) { $target = $r.Target }
        }
        if (-not $target) { throw "Could not resolve relationship $rid for tab '$TabName'" }
        $target = $target -replace '^/xl/', ''
        $target = $target -replace '^\.\./', ''
        $entryName = 'xl/' + $target

        # Shared strings: most cell text lives here, indexed by the cell's value.
        $shared = @()
        $ssXml = Read-ZipEntryText $zip 'xl/sharedStrings.xml'
        if ($ssXml) {
            $ss = [xml]$ssXml
            $ssNs = New-Object System.Xml.XmlNamespaceManager($ss.NameTable)
            $ssNs.AddNamespace('m', $main)
            foreach ($si in $ss.SelectNodes('//m:si', $ssNs)) {
                # A styled cell is split into <r> runs; concatenating the <t>
                # nodes in document order rebuilds the text, newlines included.
                $parts = @()
                foreach ($t in $si.SelectNodes('.//m:t', $ssNs)) { $parts += $t.InnerText }
                $shared += ($parts -join '')
            }
        }

        $shXml = Read-ZipEntryText $zip $entryName
        if (-not $shXml) { throw "Worksheet part $entryName missing" }
        $sh = [xml]$shXml
        $shNs = New-Object System.Xml.XmlNamespaceManager($sh.NameTable)
        $shNs.AddNamespace('m', $main)

        # Pass 1: rows as column-index -> text maps.
        $rawRows = @()
        foreach ($row in $sh.SelectNodes('//m:sheetData/m:row', $shNs)) {
            $cells = @{}
            foreach ($c in $row.SelectNodes('m:c', $shNs)) {
                $ref = $c.GetAttribute('r')
                if (-not $ref) { continue }
                $type = $c.GetAttribute('t')
                $text = ''
                if ($type -eq 's') {
                    $vNode = $c.SelectSingleNode('m:v', $shNs)
                    if ($vNode) {
                        $idx = [int]$vNode.InnerText
                        if ($idx -ge 0 -and $idx -lt $shared.Count) { $text = $shared[$idx] }
                    }
                } elseif ($type -eq 'inlineStr') {
                    $isNode = $c.SelectSingleNode('m:is', $shNs)
                    if ($isNode) {
                        $parts = @()
                        foreach ($t in $isNode.SelectNodes('.//m:t', $shNs)) { $parts += $t.InnerText }
                        $text = ($parts -join '')
                    }
                } else {
                    # Numbers, and formula cells carrying a cached value.
                    $vNode = $c.SelectSingleNode('m:v', $shNs)
                    if ($vNode) { $text = $vNode.InnerText }
                }
                if ($text -ne '') { $cells[(Get-ColumnLetter $ref)] = $text }
            }
            $rawRows += , $cells
        }

        if ($rawRows.Count -lt 1) { return @{ headers = @{}; rows = @() } }

        $header = @{}
        foreach ($k in $rawRows[0].Keys) { $header[$k] = ([string]$rawRows[0][$k]).Trim() }

        $out = @()
        for ($i = 1; $i -lt $rawRows.Count; $i++) {
            if ($rawRows[$i].Keys.Count -gt 0) { $out += , $rawRows[$i] }
        }
        return @{ headers = $header; rows = $out }
    } finally {
        $zip.Dispose()
    }
}

# ------------------------------------------------------------------ inputs ---

if (-not (Test-Path $RotationPath)) {
    throw "Rotation skeleton not found at $RotationPath. Run tools/build-rotation.ps1 first."
}
$rotation = Get-Content $RotationPath -Raw -Encoding UTF8 | ConvertFrom-Json
if (-not $rotation.slots) { throw "No slots[] in $RotationPath" }

# ------------------------------------------------------ publication horizon ---
# Each cycle's start is its earliest slot date, so the skeleton is the only
# source needed - no dependence on the sheet's Cycle Calendar, which is the tab
# that had the cycle-3 miscount.
#
# Dates are ISO, so plain string comparison orders them correctly. "Today" is
# the runner's UTC date: Eastern is UTC-4/-5, so a cycle can open a few hours
# early in local terms. Against a whole-day lead that is immaterial, and using
# UTC avoids the Windows/Linux timezone-id split ("Eastern Standard Time" vs
# "America/New_York") that would otherwise differ between local and CI runs.
$cycleStart = @{}
foreach ($g in ($rotation.slots | Group-Object { '{0}|{1}' -f $_.semester, $_.cycle })) {
    $cycleStart[$g.Name] = @($g.Group | ForEach-Object { [string]$_.date } | Sort-Object)[0]
}

$todayUtc = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd')
if ($Today) {
    $todayUtc = $Today
    Write-Host "NOTE: -Today override in effect ($Today). Not for normal runs."
}
$inv = [Globalization.CultureInfo]::InvariantCulture
$publishable = @{}
$opensOn = @{}
foreach ($k in $cycleStart.Keys) {
    $start = [datetime]::ParseExact($cycleStart[$k], 'yyyy-MM-dd', $inv)
    $open = $start.AddDays(-$PublishLeadDays).ToString('yyyy-MM-dd')
    $opensOn[$k] = $open
    if ($todayUtc -ge $open) { $publishable[$k] = $true }
}
if ($PublishLeadDays -le 0) {
    Write-Host ("Publication horizon: disabled - all {0} cycles publish in full" -f $cycleStart.Count)
} else {
    Write-Host ("Publication horizon: today {0} (UTC), lead {1} day(s) -> {2} of {3} cycles open" -f
        $todayUtc, $PublishLeadDays, $publishable.Count, $cycleStart.Count)
}

# The download MUST NOT live under docs/. The Pages artifact uploads that whole
# directory as it stands on the runner - gitignored files included - so a copy
# of the sheet parked there would be served publicly, filename disclosing the
# id. (That is exactly how the retired decks ended up downloadable from the
# live site.) .cache/ is outside the published tree.
$cacheDir = Join-Path $PSScriptRoot '.cache'
if (-not (Test-Path $cacheDir)) { New-Item -ItemType Directory -Path $cacheDir -Force | Out-Null }
$xlsxPath = Join-Path $cacheDir "sheet-$SheetId.xlsx"

# Belt and braces: clear any source file a previous version left inside docs/,
# so it cannot be picked up by the next Pages upload.
foreach ($stray in @('deck-*.pptx', 'sheet-*.xlsx', '*.tmp')) {
    Get-ChildItem -Path $dataDir -Filter $stray -ErrorAction SilentlyContinue |
        ForEach-Object {
            Write-Host ("Removing stray source file from the published tree: data/{0}" -f $_.Name)
            Remove-Item $_.FullName -Force
        }
}
$exportUrl = "https://docs.google.com/spreadsheets/d/$SheetId/export?format=xlsx"
# The URL contains the id, so log the masked tag instead of the URL.
Write-Host "Fetching xlsx export of $sheetTag"
$tmp = "$xlsxPath.tmp"
Invoke-WebRequest -Uri $exportUrl -OutFile $tmp -UseBasicParsing -TimeoutSec 120

# A permission failure returns an HTML error page, not a zip. Bail out before
# overwriting anything, so a de-shared sheet leaves the last good file intact.
$sig = [System.IO.File]::ReadAllBytes($tmp)[0..1]
if ($sig[0] -ne 0x50 -or $sig[1] -ne 0x4B) {
    Remove-Item $tmp -Force
    throw "Export did not return an .xlsx (sheet may no longer be link-shared). Aborting; previous schedule.json left intact."
}
Move-Item -Path $tmp -Destination $xlsxPath -Force

$tab = Read-XlsxTab -XlsxPath $xlsxPath -TabName $MasterTab
$rows = $tab.rows
Write-Host ("Read {0}: {1} non-empty row(s)" -f $MasterTab, $rows.Count)

# Master Data's column order is the contract: column letter -> the header texts
# that column is allowed to carry, preferred name first.
#
# C and H are BOTH headed "Lesson" in the sheet's original layout (C is the
# lesson number, H is the lesson content). That collision is why columns are
# addressed by letter and never looked up by name. The clearer "Lesson #" and
# "Lesson Plan" names are accepted as well, so renaming those two header cells
# in the sheet neither requires nor waits on a change here.
$COLS = [ordered]@{
    'A' = @('Semester')
    'B' = @('Cycle')
    'C' = @('Lesson #', 'Lesson')
    'D' = @('Track')
    'E' = @('First 5')
    'F' = @('Bring')
    'G' = @('Lit. Focus')
    'H' = @('Lesson Plan', 'Lesson')
    'I' = @('Study')
    'J' = @('Homework')
    'K' = @('Due')
}
$headerProblems = @()
foreach ($col in $COLS.Keys) {
    $actual = ''
    if ($tab.headers.ContainsKey($col)) { $actual = $tab.headers[$col] }
    if ($COLS[$col] -notcontains $actual) {
        $allowed = (($COLS[$col] | ForEach-Object { "'$_'" }) -join ' or ')
        $headerProblems += ("{0}1 is '{1}', expected {2}" -f $col, $actual, $allowed)
    }
}
if ($headerProblems.Count) {
    throw ("'{0}' tab layout has changed - refusing to guess. {1}" -f $MasterTab, ($headerProblems -join '; '))
}

# Cell accessor: blank cells are simply absent from the row.
function Get-Cell {
    param($Row, [string]$Col)
    if ($Row.ContainsKey($Col)) { return [string]$Row[$Col] }
    return ''
}

# ------------------------------------------------------------------- index ---
# Master Data is formula-driven, so blank lessons still produce rows. Only rows
# that actually carry content are indexed; the rest are left to fall through as
# empty records, which is what the board renders as a blank panel.

$allWarnings = @()
$content = @{}
$contentRows = 0

foreach ($row in $rows) {
    $semRaw    = (Get-Cell $row 'A').Trim()
    $cycleRaw  = (Get-Cell $row 'B').Trim()
    $lessonRaw = (Get-Cell $row 'C').Trim()
    $track     = (Get-Cell $row 'D').Trim().ToUpper()

    # Numeric columns arrive as "1" or "1.0" depending on the cell format.
    $sem = 0; $cycle = 0; $lesson = 0
    if (-not [int]::TryParse(($semRaw -replace '\.0+$', ''), [ref]$sem)) { continue }
    if (-not [int]::TryParse(($cycleRaw -replace '\.0+$', ''), [ref]$cycle)) { continue }
    if (-not [int]::TryParse(($lessonRaw -replace '\.0+$', ''), [ref]$lesson)) { continue }
    if (-not $TrackCourse.ContainsKey($track)) {
        $allWarnings += "unknown track '$track' at semester $sem cycle $cycle lesson $lesson"
        continue
    }

    $rec = [pscustomobject]@{
        first5    = (Join-Text  (Get-Cell $row 'E'))
        materials = (Join-Text  (Get-Cell $row 'F'))
        objective = (Join-Text  (Get-Cell $row 'G'))
        lesson    = (Split-Lines (Get-Cell $row 'H'))
        study     = (Split-Lines (Get-Cell $row 'I'))
        homework  = (Split-Lines (Get-Cell $row 'J'))
        due       = (Join-Text  (Get-Cell $row 'K'))
    }

    $has = ($rec.first5 -ne '' -or $rec.materials -ne '' -or $rec.objective -ne '' -or
            $rec.lesson.Count -gt 0 -or $rec.study.Count -gt 0 -or
            $rec.homework.Count -gt 0 -or $rec.due -ne '')
    if (-not $has) { continue }

    $key = '{0}|{1}|{2}|{3}' -f $sem, $cycle, $lesson, $track
    if ($content.ContainsKey($key)) {
        $allWarnings += "duplicate Master Data row for $key"
        continue
    }
    $content[$key] = $rec
    $contentRows++
}

# --------------------------------------------------------------------- join ---

$allRecords = @()
$matched = 0
$withheld = 0
$withheldByCycle = @{}
$usedKeys = @{}

foreach ($slot in $rotation.slots) {
    $track = [string]$slot.track
    $key = '{0}|{1}|{2}|{3}' -f $slot.semester, $slot.cycle, $slot.lessonNumber, $track
    $cycleKey = '{0}|{1}' -f $slot.semester, $slot.cycle

    $c = $null
    if ($content.ContainsKey($key)) {
        # Mark the row used whether or not it is published. A withheld cycle's
        # rows are legitimately matched to a slot; leaving them unmarked would
        # raise a "no matching rotation slot" warning for every one of them and
        # bury the real mistakes.
        $usedKeys[$key] = $true
        if ($PublishLeadDays -le 0 -or $publishable.ContainsKey($cycleKey)) {
            $c = $content[$key]
            $matched++
        } else {
            $withheld++
            if (-not $withheldByCycle.ContainsKey($cycleKey)) { $withheldByCycle[$cycleKey] = 0 }
            $withheldByCycle[$cycleKey]++
        }
    }

    $first5 = ''; $materials = ''; $objective = ''; $due = ''
    $lesson = @(); $study = @(); $homework = @()
    if ($c) {
        $first5 = $c.first5; $materials = $c.materials; $objective = $c.objective; $due = $c.due
        $lesson = $c.lesson; $study = $c.study; $homework = $c.homework
    }

    $course = ''
    if ($TrackCourse.ContainsKey($track)) { $course = $TrackCourse[$track] }

    $allRecords += [pscustomobject]@{
        date         = $slot.date
        weekday      = $slot.weekday
        rotationDay  = $slot.rotationDay
        dayType      = $slot.dayType
        dayNote      = $slot.dayNote
        period       = $slot.period
        track        = $track
        semester     = $slot.semester
        cycle        = $slot.cycle
        lessonNumber = $slot.lessonNumber
        first5       = $first5
        materials    = $materials
        objective    = $objective
        lesson       = [string[]]$lesson
        study        = [string[]]$study
        homework     = [string[]]$homework
        due          = $due
        hasContent   = ($null -ne $c)
        course       = $course
    }
}

# Content the skeleton has nowhere to put. Almost always a typo in Semester,
# Cycle or Lesson, or a lesson number past what that cycle actually holds.
foreach ($k in ($content.Keys | Sort-Object)) {
    if (-not $usedKeys.ContainsKey($k)) {
        $allWarnings += "Master Data row $k has content but no matching rotation slot"
    }
}

$dupes = @($allRecords | Group-Object { $_.date + '|' + $_.period } | Where-Object { $_.Count -gt 1 })
foreach ($d in $dupes) { $allWarnings += "duplicate record for $($d.Name)" }

$allRecords = $allRecords | Sort-Object date, period

$calendarOrdered = [ordered]@{}
foreach ($k in ($rotation.calendar.PSObject.Properties.Name | Sort-Object)) {
    $calendarOrdered[$k] = $rotation.calendar.$k
}

$sources = @(
    # No sheet id and no export URL: schedule.json is published on GitHub Pages,
    # and the sheet is meant to stay unlisted. Row counts are the useful part
    # for spotting a bad run, and they identify nothing.
    [pscustomobject]@{
        kind      = 'google-sheet'
        tab       = $MasterTab
        rowsRead  = $rows.Count
        rowsWithContent = $contentRows
    },
    [pscustomobject]@{
        kind     = 'rotation-skeleton'
        path     = 'data/rotation.json'
        frozenAt = $rotation.frozenAt
        slots    = @($rotation.slots).Count
    }
)

$payload = [pscustomobject]@{
    sources       = @($sources)
    generatedAt   = (Get-Date).ToString('o')
    schoolYear    = "$FallSchoolYear-$($FallSchoolYear + 1)"
    recordCount   = $allRecords.Count
    withContent   = (@($allRecords | Where-Object { $_.hasContent }).Count)
    matchedSlots  = $matched
    # Slots whose sheet content exists but is not yet within the publication
    # horizon, so it is deliberately absent from this file.
    publishLeadDays = $PublishLeadDays
    withheldSlots   = $withheld
    warnings      = [string[]]$allWarnings
    # date -> board day-type code (1-7, X, A, B), for the board's CAL lookup.
    calendar      = $calendarOrdered
    schedule      = @($allRecords)
}

# What moved since the last run. This is how a sheet edit gets verified, and it
# has to happen before the file is overwritten.
$changes = @()
if ($previous) {
    $prevMap = @{}
    foreach ($r in $previous.schedule) { $prevMap[$r.date + ' ' + $r.period] = $r }
    foreach ($r in $allRecords) {
        $k = $r.date + ' ' + $r.period
        if (-not $prevMap.ContainsKey($k)) { $changes += "+ $k (new)"; continue }
        if ((Get-RecordSignature $r) -ne (Get-RecordSignature $prevMap[$k])) {
            $changes += "~ $k  $($r.course)  Lesson $($r.lessonNumber)  $($r.objective)"
        }
        $prevMap.Remove($k)
    }
    foreach ($k in ($prevMap.Keys | Sort-Object)) { $changes += "- $k (gone)" }
}

# Deterministic bytes. Windows PowerShell 5.1 and the pwsh 7 on the CI runner
# disagree about both indentation and whether non-ASCII is escaped, so the same
# data serialised under each produces a different file and every run looks like
# a change. -Compress settles the whitespace; escaping non-ASCII ourselves
# settles the rest. Diffs stop being readable, which is what the change report
# above is for.
$json = $payload | ConvertTo-Json -Depth 12 -Compress
# Windows PowerShell 5.1 additionally escapes & < > ' as \u00xx for HTML safety;
# pwsh 7 leaves them literal. Settle on the literal form, which is valid JSON
# under both. The lookbehind avoids touching a sequence whose backslash is
# itself escaped.
$json = [regex]::Replace($json, '(?<!\\)\\u00(26|3[ce]|27)',
    { param($m) [string][char][Convert]::ToInt32($m.Groups[1].Value, 16) }, 'IgnoreCase')
# Then escape everything non-ASCII, which 5.1 does and 7 does not.
$json = [regex]::Replace($json, '[^\x00-\x7F]', { param($m) '\u{0:x4}' -f [int][char]$m.Value })

# generatedAt alone would differ on every run and commit a file whose data is
# unchanged, which is exactly the churn the six-hourly job must not produce.
# When nothing but the clock moved, keep the old stamp and the old bytes. The
# field then means "when the lesson data last changed", which is what the board
# reports and what anyone actually wants to know.
$stampOnly = $false
if (Test-Path $jsonPath) {
    $stampRx = '"generatedAt":"[^"]*"'
    $old = [System.IO.File]::ReadAllText($jsonPath)
    if ([regex]::Replace($json, $stampRx, '""') -eq [regex]::Replace($old, $stampRx, '""')) {
        $json = $old
        $stampOnly = $true
    }
}
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($jsonPath, $json, $utf8NoBom)

Write-Host ""
Write-Host "Wrote $jsonPath"
Write-Host "  $sheetTag / $MasterTab -> $contentRows row(s) with content"
Write-Host "  rotation slots=$(@($rotation.slots).Count)  matched=$matched  records=$($allRecords.Count)  with content=$($payload.withContent)  calendar days=$($calendarOrdered.Count)  warnings=$($allWarnings.Count)"
if ($withheld -gt 0) {
    Write-Host "  $withheld slot(s) withheld by the $PublishLeadDays-day publication horizon:"
    foreach ($k in ($withheldByCycle.Keys | Sort-Object)) {
        Write-Host ("    semester {0} cycle {1}: {2} slot(s), opens {3} (starts {4})" -f
            $k.Split('|')[0], $k.Split('|')[1], $withheldByCycle[$k], $opensOn[$k], $cycleStart[$k])
    }
}
foreach ($w in $allWarnings) { Write-Host "  ! $w" }

if ($null -eq $previous) { Write-Host "  (no previous schedule.json to compare against)" }
elseif ($stampOnly) { Write-Host "  no change at all - file left byte-identical, nothing to commit" }
elseif ($changes.Count -eq 0) { Write-Host "  no lesson content changed since the last run" }
else {
    Write-Host "  $($changes.Count) record(s) changed since the last run:"
    foreach ($c in $changes) { Write-Host "    $c" }
}
